org: kevin1
service: apiproductos

provider:
  name: aws
  runtime: nodejs20.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:648908580448:table/usuario
        - arn:aws:dynamodb:us-east-1:648908580448:table/laboratorios
        - arn:aws:dynamodb:us-east-1:648908580448:table/asignaturas
        - arn:aws:dynamodb:us-east-1:648908580448:table/parciales
        - arn:aws:dynamodb:us-east-1:648908580448:table/practicas
        - arn:aws:dynamodb:us-east-1:648908580448:table/usoEquipo
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:4200
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
functions:
  # Funciones para la tabla usuarios
  agregarUser:
    handler: src/usuarios/agregarUser.agregarUser
    events:
      - httpApi:
          path: /usuario
          method: post

  obtenerUser:
    handler: src/usuarios/obtenerUser.obtenerUser
    events:
      - httpApi:
          path: /usuario/{id}
          method: get

  eliminarUser:
    handler: src/usuarios/eliminarUser.eliminarUser
    events:
      - httpApi:
          path: /usuario/{id}
          method: delete

  actualizarUser:
    handler: src/usuarios/actualizarUser.actualizarUser
    events:
      - httpApi:
          path: /usuario/{id}
          method: put

  obtenerTodosUsuarios:
    handler: src/usuarios/obtenerTodosUsuarios.obtenerTodosUsuarios
    events:
      - httpApi:
          path: /usuarios
          method: get

  # Funciones para la tabla laboratorios
  agregarLaboratorio:
    handler: src/laboratorios/agregarLab.agregarLab
    events:
      - httpApi:
          path: /laboratorio
          method: post

  obtenerLaboratorio:
    handler: src/laboratorios/obtenerLab.obtenerLab
    events:
      - httpApi:
          path: /laboratorio/{id}
          method: get

  eliminarLaboratorio:
    handler: src/laboratorios/eliminarLab.eliminarLab
    events:
      - httpApi:
          path: /laboratorio/{id}
          method: delete

  actualizarLaboratorio:
    handler: src/laboratorios/actualizarLab.actualizarLab
    events:
      - httpApi:
          path: /laboratorio/{id}
          method: put

  # Funciones para la tabla asignaturas
  agregarAsignatura:
    handler: src/asignaturas/agregarAsig.agregarAsig
    events:
      - httpApi:
          path: /asignatura
          method: post

  obtenerAsignatura:
    handler: src/asignaturas/obtenerAsig.obtenerAsig
    events:
      - httpApi:
          path: /asignatura/{id}
          method: get

  eliminarAsignatura:
    handler: src/asignaturas/eliminarAsig.eliminarAsig
    events:
      - httpApi:
          path: /asignatura/{id}
          method: delete

  obtenerAsignaturasPorDocente:
    handler: src/asignaturas/obtenerPorDocente.obtenerAsignaturasPorDocente
    events:
      - httpApi:
          path: /asignaturas/docente/{docenteId}
          method: get
  obtenerAsignaturasPorEstudiante:
    handler: src/asignaturas/obtenerAsignaturasPorEstudiante.obtenerAsignaturasPorEstudiante
    events:
      - httpApi:
          path: /asignaturas/estudiante/{id}
          method: get

  actualizarAsignatura:
    handler: src/asignaturas/actualizarAsig.actualizarAsig
    events:
      - httpApi:
          path: /asignatura/{id}
          method: put

  obtenerTodasAsignaturas:
    handler: src/asignaturas/obtenerTodasAsignaturas.obtenerTodasAsignaturas
    events:
      - httpApi:
          path: /asignaturas
          method: get

  # Funciones para la tabla parciales
  agregarParcial:
    handler: src/parciales/agregarPar.agregarPar
    events:
      - httpApi:
          path: /parciales
          method: post

  # obtenerParciales:
  #   handler: src/parciales/obtenerPar.obtenerPar
  #   events:
  #     - httpApi:
  #         path: /parciales
  #         method: get

  obtenerTodosParciales:
    handler: src/parciales/obtenerTodosParciales.obtenerTodosParciales
    events:
      - httpApi:
          path: /parciales
          method: get

  eliminarParcial:
    handler: src/parciales/eliminarPar.eliminarPar
    events:
      - httpApi:
          path: /parciales/{id}
          method: delete

  actualizarParcial:
    handler: src/parciales/actualizarPar.actualizarPar
    events:
      - httpApi:
          path: /parciales/{id}
          method: put

  # Funciones para la tabla practicas
  agregarPractica:
    handler: src/practicas/agregarPract.agregarPract
    events:
      - httpApi:
          path: /practicas
          method: post

  obtenerPracticas:
    handler: src/practicas/obtenerPract.obtenerPract
    events:
      - httpApi:
          path: /practicas
          method: get

  eliminarPractica:
    handler: src/practicas/eliminarPract.eliminarPract
    events:
      - httpApi:
          path: /practicas/{id}
          method: delete

  actualizarPractica:
    handler: src/practicas/actualizarPract.actualizarPract
    events:
      - httpApi:
          path: /practicas/{id}
          method: put

  obtenerPracticasPorDocente:
    handler: src/practicas/obtenerPracticasPorDocente.obtenerPracticasPorDocente
    events:
      - httpApi:
          path: /practicas/docente/{docenteId}
          method: get
  # Funciones para la tabla usoEquipo
  agregarUsoEquipo:
    handler: src/usoEquipo/agregarEquip.agregarEquip
    events:
      - httpApi:
          path: /usoEquipo
          method: post

  obtenerUsoEquipo:
    handler: src/usoEquipo/obtenerEquip.obtenerEquip
    events:
      - httpApi:
          path: /usoEquipo/{id}
          method: get

  eliminarUsoEquipo:
    handler: src/usoEquipo/eliminarEquip.eliminarEquip
    events:
      - httpApi:
          path: /usoEquipo/{id}
          method: delete

  actualizarUsoEquipo:
    handler: src/usoEquipo/actualizarEquip.actualizarEquip
    events:
      - httpApi:
          path: /usoEquipo/{id}
          method: put
resources:
  Resources:
    UsuarioTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usuario
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    LaboratoriosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: laboratorios
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    AsignaturasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: asignaturas
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ParcialesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: parciales
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    PracticasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: practicas
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    UsoEquipoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usoEquipo
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
